# SCAP MVP Configuration

# Default scan settings
scan:
  timeout: 60  # Connection timeout in seconds
  parallel: 4  # Number of parallel checks to run

# Rule file locations
rules:
  default_xccdf: "U_MS_Windows_11_V2R4_STIG_SCAP_1-3_Benchmark.xml"
  default_oval: "sample_oval.xml"

# Report settings
report:
  default_format: "console"  # Options: console, json, html
  output_dir: "reports"
  include_evidence: true
  include_remediation: true

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "scap_mvp.log"
  max_size: 10485760  # 10MB
  backup_count: 3 